all.stores=Всички магазини

mail.enabled=false
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.username=keysoo.official@gmail.com
mail.smtp.password=
mail.from.email=keysoo.official@gmail.com
mail.from.name=Keysoo Protect+
